-- LINE OSS CRM D1 Schema
-- IDs are TEXT and generated by app code using crypto.randomUUID()

-- ============================================================
-- Friends
-- ============================================================
CREATE TABLE IF NOT EXISTS friends (
  id               TEXT PRIMARY KEY,
  line_user_id     TEXT UNIQUE NOT NULL,
  line_account_id  TEXT REFERENCES line_accounts(id) ON DELETE SET NULL,
  display_name     TEXT,
  picture_url      TEXT,
  status_message   TEXT,
  is_following     INTEGER NOT NULL DEFAULT 1,
  user_id          TEXT,
  ig_igsid         TEXT,
  ref_code         TEXT,
  score            INTEGER NOT NULL DEFAULT 0,
  created_at       TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f', 'now', '+9 hours')),
  updated_at       TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f', 'now', '+9 hours'))
);

CREATE INDEX IF NOT EXISTS idx_friends_line_user_id ON friends (line_user_id);
CREATE INDEX IF NOT EXISTS idx_friends_line_account_id ON friends (line_account_id);
CREATE INDEX IF NOT EXISTS idx_friends_user_id ON friends (user_id);
CREATE INDEX IF NOT EXISTS idx_friends_ig_igsid ON friends (ig_igsid);
CREATE INDEX IF NOT EXISTS idx_friends_ref_code ON friends (ref_code);

-- ============================================================
-- Tags
-- ============================================================
CREATE TABLE IF NOT EXISTS tags (
  id         TEXT PRIMARY KEY,
  name       TEXT UNIQUE NOT NULL,
  color      TEXT NOT NULL DEFAULT '#3B82F6',
  kind       TEXT NOT NULL DEFAULT 'custom' CHECK (kind IN ('system', 'custom')),
  category   TEXT,
  description TEXT,
  is_active INTEGER NOT NULL DEFAULT 1,
  is_locked INTEGER NOT NULL DEFAULT 0,
  created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f', 'now', '+9 hours')),
  updated_at TEXT
);

-- ============================================================
-- Friend <-> Tag join
-- ============================================================
CREATE TABLE IF NOT EXISTS friend_tags (
  friend_id   TEXT NOT NULL REFERENCES friends (id) ON DELETE CASCADE,
  tag_id      TEXT NOT NULL REFERENCES tags (id) ON DELETE CASCADE,
  assigned_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f', 'now', '+9 hours')),
  source      TEXT DEFAULT 'manual' CHECK (source IN ('manual', 'system', 'automation', 'reservation', 'tracked_link', 'import')),
  source_event_id TEXT,
  expires_at TEXT,
  metadata TEXT,
  PRIMARY KEY (friend_id, tag_id)
);

CREATE INDEX IF NOT EXISTS idx_friend_tags_tag_id ON friend_tags (tag_id);

-- ============================================================
-- Scenarios
-- ============================================================
CREATE TABLE IF NOT EXISTS scenarios (
  id              TEXT PRIMARY KEY,
  name            TEXT NOT NULL,
  description     TEXT,
  trigger_type    TEXT NOT NULL CHECK (trigger_type IN ('friend_add', 'tag_added', 'manual')),
  trigger_tag_id  TEXT REFERENCES tags (id) ON DELETE SET NULL,
  is_active       INTEGER NOT NULL DEFAULT 1,
  created_at      TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f', 'now', '+9 hours')),
  updated_at      TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f', 'now', '+9 hours'))
);

-- ============================================================
-- Scenario Steps
-- ============================================================
CREATE TABLE IF NOT EXISTS scenario_steps (
  id              TEXT PRIMARY KEY,
  scenario_id     TEXT NOT NULL REFERENCES scenarios (id) ON DELETE CASCADE,
  step_order      INTEGER NOT NULL,
  delay_minutes   INTEGER NOT NULL DEFAULT 0,
  message_type    TEXT NOT NULL CHECK (message_type IN ('text', 'image', 'flex')),
  message_content TEXT NOT NULL,
  created_at      TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f', 'now', '+9 hours')),
  UNIQUE (scenario_id, step_order)
);

CREATE INDEX IF NOT EXISTS idx_scenario_steps_scenario_id ON scenario_steps (scenario_id);

-- ============================================================
-- Friend Scenario Enrollments
-- ============================================================
CREATE TABLE IF NOT EXISTS friend_scenarios (
  id                 TEXT PRIMARY KEY,
  friend_id          TEXT NOT NULL REFERENCES friends (id) ON DELETE CASCADE,
  scenario_id        TEXT NOT NULL REFERENCES scenarios (id) ON DELETE CASCADE,
  current_step_order INTEGER NOT NULL DEFAULT 0,
  status             TEXT NOT NULL CHECK (status IN ('active', 'paused', 'completed', 'delivering')) DEFAULT 'active',
  started_at         TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f', 'now', '+9 hours')),
  next_delivery_at   TEXT,
  updated_at         TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f', 'now', '+9 hours'))
);

CREATE INDEX IF NOT EXISTS idx_friend_scenarios_next_delivery_at ON friend_scenarios (next_delivery_at);
CREATE INDEX IF NOT EXISTS idx_friend_scenarios_status ON friend_scenarios (status);
CREATE INDEX IF NOT EXISTS idx_friend_scenarios_friend_id ON friend_scenarios (friend_id);
CREATE UNIQUE INDEX IF NOT EXISTS idx_friend_scenarios_unique ON friend_scenarios (friend_id, scenario_id) WHERE status != 'completed';

-- ============================================================
-- Broadcasts
-- ============================================================
CREATE TABLE IF NOT EXISTS broadcasts (
  id              TEXT PRIMARY KEY,
  title           TEXT NOT NULL,
  message_type    TEXT NOT NULL CHECK (message_type IN ('text', 'image', 'flex')),
  message_content TEXT NOT NULL,
  target_type     TEXT NOT NULL CHECK (target_type IN ('all', 'tag')) DEFAULT 'all',
  target_tag_id   TEXT REFERENCES tags (id) ON DELETE SET NULL,
  status          TEXT NOT NULL CHECK (status IN ('draft', 'scheduled', 'sending', 'sent')) DEFAULT 'draft',
  scheduled_at    TEXT,
  sent_at         TEXT,
  total_count     INTEGER NOT NULL DEFAULT 0,
  success_count   INTEGER NOT NULL DEFAULT 0,
  line_request_id   TEXT,
  aggregation_unit  TEXT,
  batch_offset    INTEGER NOT NULL DEFAULT 0,
  segment_conditions TEXT,
  created_at      TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f', 'now', '+9 hours'))
);

CREATE INDEX IF NOT EXISTS idx_broadcasts_status ON broadcasts (status);

-- ============================================================
--- Account Settings
--- ============================================================
CREATE TABLE IF NOT EXISTS account_settings (
  id              TEXT PRIMARY KEY,
  line_account_id TEXT NOT NULL,
  key             TEXT NOT NULL,
  value           TEXT NOT NULL,
  created_at      TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f', 'now', '+9 hours')),
  updated_at      TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f', 'now', '+9 hours')),
  UNIQUE(line_account_id, key)
);

-- ============================================================
-- Broadcast Insights
-- ============================================================
CREATE TABLE IF NOT EXISTS broadcast_insights (
  id                  TEXT PRIMARY KEY,
  broadcast_id        TEXT NOT NULL REFERENCES broadcasts(id) ON DELETE CASCADE,
  delivered           INTEGER,
  unique_impression   INTEGER,
  unique_click        INTEGER,
  unique_media_played INTEGER,
  open_rate           REAL,
  click_rate          REAL,
  raw_response        TEXT,
  status              TEXT NOT NULL CHECK (status IN ('pending', 'ready', 'failed')),
  retry_count         INTEGER NOT NULL DEFAULT 0,
  fetched_at          TEXT,
  created_at          TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f', 'now', '+9 hours'))
);

CREATE INDEX IF NOT EXISTS idx_broadcast_insights_broadcast_id ON broadcast_insights(broadcast_id);
CREATE INDEX IF NOT EXISTS idx_broadcast_insights_status ON broadcast_insights(status);

-- ============================================================
-- Messages Log
-- ============================================================
CREATE TABLE IF NOT EXISTS messages_log (
  id               TEXT PRIMARY KEY,
  friend_id        TEXT NOT NULL REFERENCES friends (id) ON DELETE CASCADE,
  direction        TEXT NOT NULL CHECK (direction IN ('incoming', 'outgoing')),
  message_type     TEXT NOT NULL,
  content          TEXT NOT NULL,
  broadcast_id     TEXT REFERENCES broadcasts (id) ON DELETE SET NULL,
  scenario_step_id TEXT REFERENCES scenario_steps (id) ON DELETE SET NULL,
  delivery_type    TEXT CHECK (delivery_type IN ('push', 'reply', 'test')),
  source           TEXT,
  created_at       TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f', 'now', '+9 hours'))
);

CREATE INDEX IF NOT EXISTS idx_messages_log_friend_id ON messages_log (friend_id);
CREATE INDEX IF NOT EXISTS idx_messages_log_created_at ON messages_log (created_at);
CREATE INDEX IF NOT EXISTS idx_messages_log_friend_source ON messages_log (friend_id, source);
CREATE INDEX IF NOT EXISTS idx_messages_log_friend_direction_created ON messages_log (friend_id, direction, created_at);

-- ============================================================
-- Auto Replies
-- ============================================================
CREATE TABLE IF NOT EXISTS auto_replies (
  id               TEXT PRIMARY KEY,
  keyword          TEXT NOT NULL,
  match_type       TEXT NOT NULL CHECK (match_type IN ('exact', 'contains')) DEFAULT 'exact',
  response_type    TEXT NOT NULL DEFAULT 'text',
  response_content TEXT NOT NULL,
  line_account_id  TEXT DEFAULT NULL,
  is_active        INTEGER NOT NULL DEFAULT 1,
  created_at       TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f', 'now', '+9 hours'))
);

-- ============================================================
-- Admin Users
-- ============================================================
CREATE TABLE IF NOT EXISTS admin_users (
  id            TEXT PRIMARY KEY,
  email         TEXT NOT NULL UNIQUE,
  password_hash TEXT NOT NULL,
  created_at    TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f', 'now', '+9 hours'))
);

-- ============================================================
-- Round 2: Internal UUID Users (Cross-Account)
-- ============================================================
CREATE TABLE IF NOT EXISTS users (
  id           TEXT PRIMARY KEY,
  email        TEXT,
  phone        TEXT,
  external_id  TEXT,
  display_name TEXT,
  created_at   TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f', 'now', '+9 hours')),
  updated_at   TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f', 'now', '+9 hours'))
);

CREATE INDEX IF NOT EXISTS idx_users_email ON users (email);
CREATE INDEX IF NOT EXISTS idx_users_phone ON users (phone);
CREATE INDEX IF NOT EXISTS idx_users_external_id ON users (external_id);

-- ============================================================
-- Round 2: LINE Account Management (Multi-Account)
-- ============================================================
CREATE TABLE IF NOT EXISTS line_accounts (
  id                   TEXT PRIMARY KEY,
  channel_id           TEXT NOT NULL UNIQUE,
  name                 TEXT NOT NULL,
  channel_access_token TEXT NOT NULL,
  channel_secret       TEXT NOT NULL,
  is_active            INTEGER NOT NULL DEFAULT 1,
  created_at           TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f', 'now', '+9 hours')),
  updated_at           TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f', 'now', '+9 hours'))
);

-- ============================================================
-- Round 2: Conversion Points (CV Tracking)
-- ============================================================
CREATE TABLE IF NOT EXISTS conversion_points (
  id         TEXT PRIMARY KEY,
  name       TEXT NOT NULL,
  event_type TEXT NOT NULL,
  value      REAL,
  created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f', 'now', '+9 hours'))
);

-- ============================================================
-- Round 2: Conversion Events (CV Records)
-- ============================================================
CREATE TABLE IF NOT EXISTS conversion_events (
  id                  TEXT PRIMARY KEY,
  conversion_point_id TEXT NOT NULL REFERENCES conversion_points (id) ON DELETE CASCADE,
  friend_id           TEXT NOT NULL REFERENCES friends (id) ON DELETE CASCADE,
  user_id             TEXT,
  affiliate_code      TEXT,
  metadata            TEXT,
  created_at          TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f', 'now', '+9 hours'))
);

CREATE INDEX IF NOT EXISTS idx_conversion_events_point ON conversion_events (conversion_point_id);
CREATE INDEX IF NOT EXISTS idx_conversion_events_friend ON conversion_events (friend_id);
CREATE INDEX IF NOT EXISTS idx_conversion_events_affiliate ON conversion_events (affiliate_code);

-- ============================================================
-- Round 2: Affiliates
-- ============================================================
CREATE TABLE IF NOT EXISTS affiliates (
  id              TEXT PRIMARY KEY,
  name            TEXT NOT NULL,
  code            TEXT NOT NULL UNIQUE,
  commission_rate REAL NOT NULL DEFAULT 0,
  is_active       INTEGER NOT NULL DEFAULT 1,
  created_at      TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f', 'now', '+9 hours'))
);

-- ============================================================
-- Round 2: Affiliate Clicks
-- ============================================================
CREATE TABLE IF NOT EXISTS affiliate_clicks (
  id           TEXT PRIMARY KEY,
  affiliate_id TEXT NOT NULL REFERENCES affiliates (id) ON DELETE CASCADE,
  url          TEXT,
  ip_address   TEXT,
  created_at   TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f', 'now', '+9 hours'))
);

CREATE INDEX IF NOT EXISTS idx_affiliate_clicks_affiliate ON affiliate_clicks (affiliate_id);

-- ============================================================
-- Round 3: Webhook IN/OUT
-- ============================================================
CREATE TABLE IF NOT EXISTS incoming_webhooks (
  id          TEXT PRIMARY KEY,
  name        TEXT NOT NULL,
  source_type TEXT NOT NULL DEFAULT 'custom',
  secret      TEXT,
  is_active   INTEGER NOT NULL DEFAULT 1,
  created_at  TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f', 'now', '+9 hours')),
  updated_at  TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f', 'now', '+9 hours'))
);

CREATE TABLE IF NOT EXISTS outgoing_webhooks (
  id          TEXT PRIMARY KEY,
  name        TEXT NOT NULL,
  url         TEXT NOT NULL,
  event_types TEXT NOT NULL DEFAULT '[]',
  secret      TEXT,
  is_active   INTEGER NOT NULL DEFAULT 1,
  created_at  TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f', 'now', '+9 hours')),
  updated_at  TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f', 'now', '+9 hours'))
);

-- ============================================================
-- Round 3: Google Calendar
-- ============================================================
CREATE TABLE IF NOT EXISTS google_calendar_connections (
  id            TEXT PRIMARY KEY,
  calendar_id   TEXT NOT NULL,
  access_token  TEXT,
  access_token_expires_at TEXT,
  refresh_token TEXT,
  api_key       TEXT,
  auth_type     TEXT NOT NULL DEFAULT 'api_key',
  is_active     INTEGER NOT NULL DEFAULT 1,
  created_at    TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f', 'now', '+9 hours')),
  updated_at    TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f', 'now', '+9 hours'))
);

CREATE TABLE IF NOT EXISTS calendar_bookings (
  id             TEXT PRIMARY KEY,
  connection_id  TEXT NOT NULL REFERENCES google_calendar_connections (id) ON DELETE CASCADE,
  friend_id      TEXT REFERENCES friends (id) ON DELETE SET NULL,
  event_id       TEXT,
  title          TEXT NOT NULL,
  start_at       TEXT NOT NULL,
  end_at         TEXT NOT NULL,
  status         TEXT NOT NULL DEFAULT 'confirmed' CHECK (status IN ('confirmed', 'cancelled', 'completed')),
  metadata       TEXT,
  created_at     TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f', 'now', '+9 hours')),
  updated_at     TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f', 'now', '+9 hours'))
);

CREATE INDEX IF NOT EXISTS idx_calendar_bookings_friend ON calendar_bookings (friend_id);
CREATE INDEX IF NOT EXISTS idx_calendar_bookings_start ON calendar_bookings (start_at);

-- ============================================================
-- Round 3: リマインダ配信
-- ============================================================
CREATE TABLE IF NOT EXISTS reminders (
  id          TEXT PRIMARY KEY,
  name        TEXT NOT NULL,
  description TEXT,
  is_active   INTEGER NOT NULL DEFAULT 1,
  created_at  TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f', 'now', '+9 hours')),
  updated_at  TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f', 'now', '+9 hours'))
);

CREATE TABLE IF NOT EXISTS reminder_steps (
  id              TEXT PRIMARY KEY,
  reminder_id     TEXT NOT NULL REFERENCES reminders (id) ON DELETE CASCADE,
  offset_minutes  INTEGER NOT NULL,
  message_type    TEXT NOT NULL CHECK (message_type IN ('text', 'image', 'flex')),
  message_content TEXT NOT NULL,
  created_at      TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f', 'now', '+9 hours'))
);

CREATE INDEX IF NOT EXISTS idx_reminder_steps_reminder ON reminder_steps (reminder_id);

CREATE TABLE IF NOT EXISTS friend_reminders (
  id              TEXT PRIMARY KEY,
  friend_id       TEXT NOT NULL REFERENCES friends (id) ON DELETE CASCADE,
  reminder_id     TEXT NOT NULL REFERENCES reminders (id) ON DELETE CASCADE,
  target_date     TEXT NOT NULL,
  status          TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'completed', 'cancelled')),
  created_at      TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f', 'now', '+9 hours')),
  updated_at      TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f', 'now', '+9 hours'))
);

CREATE INDEX IF NOT EXISTS idx_friend_reminders_status ON friend_reminders (status);
CREATE INDEX IF NOT EXISTS idx_friend_reminders_friend ON friend_reminders (friend_id);

CREATE TABLE IF NOT EXISTS friend_reminder_deliveries (
  id                TEXT PRIMARY KEY,
  friend_reminder_id TEXT NOT NULL REFERENCES friend_reminders (id) ON DELETE CASCADE,
  reminder_step_id  TEXT NOT NULL REFERENCES reminder_steps (id) ON DELETE CASCADE,
  delivered_at      TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f', 'now', '+9 hours')),
  UNIQUE (friend_reminder_id, reminder_step_id)
);

-- ============================================================
-- Round 3: スコアリング
-- ============================================================
CREATE TABLE IF NOT EXISTS scoring_rules (
  id          TEXT PRIMARY KEY,
  name        TEXT NOT NULL,
  event_type  TEXT NOT NULL,
  score_value INTEGER NOT NULL,
  is_active   INTEGER NOT NULL DEFAULT 1,
  created_at  TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f', 'now', '+9 hours')),
  updated_at  TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f', 'now', '+9 hours'))
);

CREATE TABLE IF NOT EXISTS friend_scores (
  id              TEXT PRIMARY KEY,
  friend_id       TEXT NOT NULL REFERENCES friends (id) ON DELETE CASCADE,
  scoring_rule_id TEXT REFERENCES scoring_rules (id) ON DELETE SET NULL,
  score_change    INTEGER NOT NULL,
  reason          TEXT,
  created_at      TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f', 'now', '+9 hours'))
);

CREATE INDEX IF NOT EXISTS idx_friend_scores_friend ON friend_scores (friend_id);
CREATE INDEX IF NOT EXISTS idx_friend_scores_created ON friend_scores (created_at);

-- ============================================================
-- Round 3: テンプレート管理
-- ============================================================
CREATE TABLE IF NOT EXISTS templates (
  id              TEXT PRIMARY KEY,
  name            TEXT NOT NULL,
  category        TEXT NOT NULL DEFAULT 'general',
  message_type    TEXT NOT NULL CHECK (message_type IN ('text', 'image', 'flex', 'carousel')),
  message_content TEXT NOT NULL,
  created_at      TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f', 'now', '+9 hours')),
  updated_at      TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f', 'now', '+9 hours'))
);

CREATE INDEX IF NOT EXISTS idx_templates_category ON templates (category);

-- ============================================================
-- Round 3: オペレーター/チャット
-- ============================================================
CREATE TABLE IF NOT EXISTS operators (
  id         TEXT PRIMARY KEY,
  name       TEXT NOT NULL,
  email      TEXT NOT NULL UNIQUE,
  role       TEXT NOT NULL DEFAULT 'operator' CHECK (role IN ('admin', 'operator')),
  is_active  INTEGER NOT NULL DEFAULT 1,
  created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f', 'now', '+9 hours')),
  updated_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f', 'now', '+9 hours'))
);

CREATE TABLE IF NOT EXISTS chats (
  id            TEXT PRIMARY KEY,
  friend_id     TEXT NOT NULL REFERENCES friends (id) ON DELETE CASCADE,
  operator_id   TEXT REFERENCES operators (id) ON DELETE SET NULL,
  line_account_id TEXT,
  status        TEXT NOT NULL DEFAULT 'unread' CHECK (status IN ('unread', 'in_progress', 'resolved')),
  notes         TEXT,
  last_message_at TEXT,
  created_at    TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f', 'now', '+9 hours')),
  updated_at    TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f', 'now', '+9 hours'))
);

CREATE INDEX IF NOT EXISTS idx_chats_friend ON chats (friend_id);
CREATE INDEX IF NOT EXISTS idx_chats_operator ON chats (operator_id);
CREATE INDEX IF NOT EXISTS idx_chats_status ON chats (status);
CREATE INDEX IF NOT EXISTS idx_chats_line_account_id ON chats (line_account_id);

-- ============================================================
-- External customer profiles for generic console v2
-- ============================================================
CREATE TABLE IF NOT EXISTS external_customer_profiles (
  id          TEXT PRIMARY KEY,
  source      TEXT NOT NULL,
  external_id TEXT,
  name        TEXT,
  phone       TEXT,
  email       TEXT,
  metadata    TEXT NOT NULL DEFAULT '{}',
  created_at  TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f', 'now', '+9 hours')),
  updated_at  TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f', 'now', '+9 hours'))
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_external_customer_profiles_source_external
ON external_customer_profiles (source, external_id)
WHERE external_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_external_customer_profiles_phone ON external_customer_profiles (phone);
CREATE INDEX IF NOT EXISTS idx_external_customer_profiles_email ON external_customer_profiles (email);
CREATE INDEX IF NOT EXISTS idx_external_customer_profiles_name ON external_customer_profiles (name);

CREATE TABLE IF NOT EXISTS friend_external_customer_links (
  id                   TEXT PRIMARY KEY,
  friend_id            TEXT NOT NULL REFERENCES friends (id) ON DELETE CASCADE,
  external_customer_id TEXT NOT NULL REFERENCES external_customer_profiles (id) ON DELETE CASCADE,
  link_method          TEXT NOT NULL CHECK (link_method IN ('manual', 'phone', 'email', 'import')),
  confidence           INTEGER NOT NULL DEFAULT 100,
  created_at           TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f', 'now', '+9 hours')),
  UNIQUE(friend_id, external_customer_id)
);

CREATE INDEX IF NOT EXISTS idx_friend_external_customer_links_friend ON friend_external_customer_links (friend_id);
CREATE INDEX IF NOT EXISTS idx_friend_external_customer_links_customer ON friend_external_customer_links (external_customer_id);

CREATE TABLE IF NOT EXISTS customer_notes (
  id                   TEXT PRIMARY KEY,
  friend_id            TEXT REFERENCES friends (id) ON DELETE CASCADE,
  external_customer_id TEXT REFERENCES external_customer_profiles (id) ON DELETE CASCADE,
  note                 TEXT NOT NULL,
  created_by           TEXT,
  created_at           TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f', 'now', '+9 hours')),
  updated_at           TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f', 'now', '+9 hours'))
);

CREATE INDEX IF NOT EXISTS idx_customer_notes_friend ON customer_notes (friend_id);
CREATE INDEX IF NOT EXISTS idx_customer_notes_external_customer ON customer_notes (external_customer_id);

-- ============================================================
-- Round 3: 通知機能
-- ============================================================
CREATE TABLE IF NOT EXISTS notification_rules (
  id           TEXT PRIMARY KEY,
  name         TEXT NOT NULL,
  event_type   TEXT NOT NULL,
  conditions   TEXT NOT NULL DEFAULT '{}',
  channels     TEXT NOT NULL DEFAULT '["webhook"]',
  is_active    INTEGER NOT NULL DEFAULT 1,
  created_at   TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f', 'now', '+9 hours')),
  updated_at   TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f', 'now', '+9 hours'))
);

CREATE TABLE IF NOT EXISTS notifications (
  id              TEXT PRIMARY KEY,
  rule_id         TEXT REFERENCES notification_rules (id) ON DELETE SET NULL,
  event_type      TEXT NOT NULL,
  title           TEXT NOT NULL,
  body            TEXT NOT NULL,
  channel         TEXT NOT NULL,
  status          TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'sent', 'failed')),
  metadata        TEXT,
  created_at      TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f', 'now', '+9 hours'))
);

CREATE INDEX IF NOT EXISTS idx_notifications_status ON notifications (status);
CREATE INDEX IF NOT EXISTS idx_notifications_created ON notifications (created_at);

-- ============================================================
-- Round 3: Stripe決済連携
-- ============================================================
CREATE TABLE IF NOT EXISTS stripe_events (
  id               TEXT PRIMARY KEY,
  stripe_event_id  TEXT NOT NULL UNIQUE,
  event_type       TEXT NOT NULL,
  friend_id        TEXT REFERENCES friends (id) ON DELETE SET NULL,
  amount           REAL,
  currency         TEXT,
  metadata         TEXT,
  processed_at     TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f', 'now', '+9 hours'))
);

CREATE INDEX IF NOT EXISTS idx_stripe_events_friend ON stripe_events (friend_id);
CREATE INDEX IF NOT EXISTS idx_stripe_events_type ON stripe_events (event_type);

-- ============================================================
-- Round 3: BAN検知 & リカバリ
-- ============================================================
CREATE TABLE IF NOT EXISTS account_health_logs (
  id              TEXT PRIMARY KEY,
  line_account_id TEXT NOT NULL,
  error_code      INTEGER,
  error_count     INTEGER NOT NULL DEFAULT 0,
  check_period    TEXT NOT NULL,
  risk_level      TEXT NOT NULL DEFAULT 'normal' CHECK (risk_level IN ('normal', 'warning', 'danger')),
  created_at      TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f', 'now', '+9 hours'))
);

CREATE INDEX IF NOT EXISTS idx_health_logs_account ON account_health_logs (line_account_id);

CREATE TABLE IF NOT EXISTS account_migrations (
  id               TEXT PRIMARY KEY,
  from_account_id  TEXT NOT NULL,
  to_account_id    TEXT NOT NULL,
  status           TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'in_progress', 'completed', 'failed')),
  migrated_count   INTEGER NOT NULL DEFAULT 0,
  total_count      INTEGER NOT NULL DEFAULT 0,
  created_at       TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f', 'now', '+9 hours')),
  completed_at     TEXT
);

-- ============================================================
-- Round 3: アクション自動化
-- ============================================================
CREATE TABLE IF NOT EXISTS automations (
  id          TEXT PRIMARY KEY,
  name        TEXT NOT NULL,
  description TEXT,
  event_type  TEXT NOT NULL,
  conditions  TEXT NOT NULL DEFAULT '{}',
  actions     TEXT NOT NULL DEFAULT '[]',
  is_active   INTEGER NOT NULL DEFAULT 1,
  priority    INTEGER NOT NULL DEFAULT 0,
  created_at  TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f', 'now', '+9 hours')),
  updated_at  TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f', 'now', '+9 hours'))
);

CREATE INDEX IF NOT EXISTS idx_automations_event ON automations (event_type);
CREATE INDEX IF NOT EXISTS idx_automations_active ON automations (is_active);

CREATE TABLE IF NOT EXISTS automation_logs (
  id             TEXT PRIMARY KEY,
  automation_id  TEXT NOT NULL REFERENCES automations (id) ON DELETE CASCADE,
  friend_id      TEXT REFERENCES friends (id) ON DELETE SET NULL,
  event_data     TEXT,
  actions_result TEXT,
  status         TEXT NOT NULL DEFAULT 'success' CHECK (status IN ('success', 'partial', 'failed')),
  created_at     TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f', 'now', '+9 hours'))
);

CREATE INDEX IF NOT EXISTS idx_automation_logs_automation ON automation_logs (automation_id);

-- ============================================================
-- Entry Routes / Ref Tracking
-- ============================================================
CREATE TABLE IF NOT EXISTS entry_routes (
  id           TEXT PRIMARY KEY,
  ref_code     TEXT UNIQUE NOT NULL,
  name         TEXT NOT NULL,
  tag_id       TEXT REFERENCES tags (id) ON DELETE SET NULL,
  scenario_id  TEXT REFERENCES scenarios (id) ON DELETE SET NULL,
  redirect_url TEXT,
  is_active    INTEGER NOT NULL DEFAULT 1,
  created_at   TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f', 'now', '+9 hours')),
  updated_at   TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f', 'now', '+9 hours'))
);

CREATE TABLE IF NOT EXISTS ref_tracking (
  id             TEXT PRIMARY KEY,
  ref_code       TEXT NOT NULL,
  friend_id      TEXT REFERENCES friends (id) ON DELETE CASCADE,
  entry_route_id TEXT REFERENCES entry_routes (id) ON DELETE SET NULL,
  source_url     TEXT,
  fbclid         TEXT,
  gclid          TEXT,
  twclid         TEXT,
  ttclid         TEXT,
  utm_source     TEXT,
  utm_medium     TEXT,
  utm_campaign   TEXT,
  user_agent     TEXT,
  ip_address     TEXT,
  created_at     TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f', 'now', '+9 hours'))
);

CREATE INDEX IF NOT EXISTS idx_entry_routes_ref ON entry_routes (ref_code);
CREATE INDEX IF NOT EXISTS idx_ref_tracking_ref ON ref_tracking (ref_code);
CREATE INDEX IF NOT EXISTS idx_ref_tracking_friend ON ref_tracking (friend_id);
CREATE INDEX IF NOT EXISTS idx_ref_tracking_entry_route ON ref_tracking (entry_route_id);

-- ============================================================
-- Tracked Links
-- ============================================================
CREATE TABLE IF NOT EXISTS tracked_links (
  id                TEXT PRIMARY KEY,
  name              TEXT NOT NULL,
  original_url      TEXT NOT NULL,
  tag_id            TEXT REFERENCES tags (id) ON DELETE SET NULL,
  scenario_id       TEXT REFERENCES scenarios (id) ON DELETE SET NULL,
  intro_template_id TEXT REFERENCES message_templates (id) ON DELETE SET NULL,
  reward_template_id TEXT REFERENCES message_templates (id) ON DELETE SET NULL,
  is_active         INTEGER NOT NULL DEFAULT 1,
  click_count       INTEGER NOT NULL DEFAULT 0,
  created_at        TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f', 'now', '+9 hours')),
  updated_at        TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f', 'now', '+9 hours'))
);

CREATE TABLE IF NOT EXISTS link_clicks (
  id              TEXT PRIMARY KEY,
  tracked_link_id TEXT NOT NULL REFERENCES tracked_links (id) ON DELETE CASCADE,
  friend_id       TEXT REFERENCES friends (id) ON DELETE SET NULL,
  clicked_at      TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f', 'now', '+9 hours'))
);

CREATE INDEX IF NOT EXISTS idx_link_clicks_link ON link_clicks (tracked_link_id);
CREATE INDEX IF NOT EXISTS idx_link_clicks_friend ON link_clicks (friend_id);

-- ============================================================
-- User Events / Event Definitions
-- ============================================================
CREATE TABLE IF NOT EXISTS user_events (
  id              TEXT PRIMARY KEY,
  line_account_id TEXT,
  friend_id       TEXT REFERENCES friends (id) ON DELETE SET NULL,
  line_user_id    TEXT,
  event_type      TEXT NOT NULL,
  event_name      TEXT,
  event_source    TEXT NOT NULL DEFAULT 'system'
    CHECK (event_source IN ('line', 'liff', 'web', 'reservation', 'jalan', 'gmail', 'tracked_link', 'broadcast', 'automation', 'system')),
  subject_type    TEXT,
  subject_id      TEXT,
  occurred_at     TEXT NOT NULL,
  received_at     TEXT NOT NULL,
  session_id      TEXT,
  request_id      TEXT,
  idempotency_key TEXT,
  metadata        TEXT NOT NULL DEFAULT '{}',
  created_at      TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f', 'now', '+9 hours'))
);

CREATE INDEX IF NOT EXISTS idx_user_events_friend_time ON user_events (friend_id, occurred_at);
CREATE INDEX IF NOT EXISTS idx_user_events_type_time ON user_events (event_type, occurred_at);
CREATE INDEX IF NOT EXISTS idx_user_events_subject ON user_events (subject_type, subject_id);
CREATE INDEX IF NOT EXISTS idx_user_events_line_account ON user_events (line_account_id, occurred_at);
CREATE UNIQUE INDEX IF NOT EXISTS uniq_user_events_idempotency_key
  ON user_events (idempotency_key)
  WHERE idempotency_key IS NOT NULL;

CREATE TABLE IF NOT EXISTS event_definitions (
  id          TEXT PRIMARY KEY,
  event_type  TEXT NOT NULL UNIQUE,
  name        TEXT NOT NULL,
  category    TEXT NOT NULL,
  description TEXT,
  is_system   INTEGER NOT NULL DEFAULT 0,
  is_active   INTEGER NOT NULL DEFAULT 1,
  created_at  TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f', 'now', '+9 hours')),
  updated_at  TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f', 'now', '+9 hours'))
);

CREATE TABLE IF NOT EXISTS event_tag_rules (
  id         TEXT PRIMARY KEY,
  name       TEXT NOT NULL,
  event_type TEXT NOT NULL,
  conditions TEXT NOT NULL DEFAULT '{}',
  action     TEXT NOT NULL CHECK (action IN ('add_tag', 'remove_tag')),
  tag_id     TEXT NOT NULL REFERENCES tags (id) ON DELETE CASCADE,
  priority   INTEGER NOT NULL DEFAULT 0,
  is_active  INTEGER NOT NULL DEFAULT 1,
  created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f', 'now', '+9 hours')),
  updated_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f', 'now', '+9 hours'))
);

CREATE INDEX IF NOT EXISTS idx_event_tag_rules_event ON event_tag_rules (event_type, is_active, priority);

-- ============================================================
-- Forms
-- ============================================================
CREATE TABLE IF NOT EXISTS forms (
  id                             TEXT PRIMARY KEY,
  name                           TEXT NOT NULL,
  description                    TEXT,
  fields                         TEXT NOT NULL DEFAULT '[]',
  on_submit_tag_id               TEXT REFERENCES tags (id) ON DELETE SET NULL,
  on_submit_scenario_id          TEXT REFERENCES scenarios (id) ON DELETE SET NULL,
  on_submit_message_type         TEXT CHECK (on_submit_message_type IN ('text', 'flex')) DEFAULT NULL,
  on_submit_message_content      TEXT DEFAULT NULL,
  on_submit_webhook_url          TEXT,
  on_submit_webhook_headers      TEXT,
  on_submit_webhook_fail_message TEXT,
  save_to_metadata               INTEGER NOT NULL DEFAULT 1,
  is_active                      INTEGER NOT NULL DEFAULT 1,
  submit_count                   INTEGER NOT NULL DEFAULT 0,
  created_at                     TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f', 'now', '+9 hours')),
  updated_at                     TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f', 'now', '+9 hours'))
);

CREATE TABLE IF NOT EXISTS form_submissions (
  id         TEXT PRIMARY KEY,
  form_id    TEXT NOT NULL REFERENCES forms (id) ON DELETE CASCADE,
  friend_id  TEXT REFERENCES friends (id) ON DELETE SET NULL,
  data       TEXT NOT NULL DEFAULT '{}',
  created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f', 'now', '+9 hours'))
);

CREATE TABLE IF NOT EXISTS form_opens (
  id          TEXT PRIMARY KEY,
  form_id     TEXT NOT NULL REFERENCES forms (id) ON DELETE CASCADE,
  friend_id   TEXT REFERENCES friends (id) ON DELETE SET NULL,
  friend_name TEXT,
  opened_at   TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f', 'now', '+9 hours'))
);

CREATE INDEX IF NOT EXISTS idx_form_submissions_form ON form_submissions (form_id);
CREATE INDEX IF NOT EXISTS idx_form_submissions_friend ON form_submissions (friend_id);
CREATE INDEX IF NOT EXISTS idx_form_opens_form ON form_opens (form_id, opened_at);

-- ============================================================
-- Ad Platform Configuration
-- ============================================================
CREATE TABLE IF NOT EXISTS ad_platforms (
  id           TEXT PRIMARY KEY,
  name         TEXT NOT NULL,
  display_name TEXT,
  config       TEXT NOT NULL DEFAULT '{}',
  is_active    INTEGER DEFAULT 1,
  created_at   TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f', 'now', '+9 hours')),
  updated_at   TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f', 'now', '+9 hours'))
);

-- ============================================================
-- Ad Conversion Logs
-- ============================================================
CREATE TABLE IF NOT EXISTS ad_conversion_logs (
  id                  TEXT PRIMARY KEY,
  ad_platform_id      TEXT NOT NULL,
  friend_id           TEXT NOT NULL,
  conversion_point_id TEXT,
  event_name          TEXT NOT NULL,
  click_id            TEXT,
  click_id_type       TEXT,
  status              TEXT DEFAULT 'pending',
  request_body        TEXT,
  response_body       TEXT,
  error_message       TEXT,
  created_at          TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f', 'now', '+9 hours'))
);

CREATE INDEX IF NOT EXISTS idx_ad_conversion_logs_platform ON ad_conversion_logs (ad_platform_id);
CREATE INDEX IF NOT EXISTS idx_ad_conversion_logs_friend ON ad_conversion_logs (friend_id);
CREATE INDEX IF NOT EXISTS idx_ad_conversion_logs_status ON ad_conversion_logs (status);

-- Staff member accounts with role-based access control
CREATE TABLE IF NOT EXISTS staff_members (
  id         TEXT PRIMARY KEY,
  name       TEXT NOT NULL,
  email      TEXT,
  role       TEXT NOT NULL CHECK (role IN ('owner', 'admin', 'staff')),
  api_key    TEXT UNIQUE NOT NULL,
  is_active  INTEGER NOT NULL DEFAULT 1,
  created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f', 'now', '+9 hours')),
  updated_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f', 'now', '+9 hours'))
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_staff_members_api_key ON staff_members(api_key);
CREATE INDEX IF NOT EXISTS idx_staff_members_role ON staff_members(role);

-- Reusable message templates (text or Flex) for reward messages in campaigns
CREATE TABLE IF NOT EXISTS message_templates (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  message_type TEXT NOT NULL CHECK (message_type IN ('text', 'flex')),
  message_content TEXT NOT NULL,
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  updated_at TEXT NOT NULL DEFAULT (datetime('now'))
);

-- Pool accounts — multiple LINE accounts per traffic pool for distribution
CREATE TABLE IF NOT EXISTS pool_accounts (
  id TEXT PRIMARY KEY,
  pool_id TEXT NOT NULL REFERENCES traffic_pools(id) ON DELETE CASCADE,
  line_account_id TEXT NOT NULL REFERENCES line_accounts(id) ON DELETE CASCADE,
  is_active INTEGER NOT NULL DEFAULT 1,
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  UNIQUE(pool_id, line_account_id)
);

-- ============================================================
-- Reservation System
-- ============================================================
CREATE TABLE IF NOT EXISTS reservation_customer_profiles (
  user_id TEXT PRIMARY KEY REFERENCES users (id) ON DELETE CASCADE,
  status TEXT NOT NULL DEFAULT 'prospect'
    CHECK (status IN ('prospect', 'reserved', 'visited', 'cancelled', 'inactive')),
  source TEXT NOT NULL DEFAULT 'line'
    CHECK (source IN ('line', 'web', 'jalan', 'phone', 'gmail', 'admin', 'mcp', 'unknown')),
  memo TEXT,
  metadata TEXT NOT NULL DEFAULT '{}',
  first_reserved_at TEXT,
  last_reserved_at TEXT,
  first_visited_at TEXT,
  last_visited_at TEXT,
  created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f', 'now', '+9 hours')),
  updated_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f', 'now', '+9 hours'))
);

CREATE TABLE IF NOT EXISTS reservation_resources (
  id TEXT PRIMARY KEY,
  line_account_id TEXT REFERENCES line_accounts (id) ON DELETE SET NULL,
  name TEXT NOT NULL,
  description TEXT,
  default_duration_minutes INTEGER NOT NULL DEFAULT 60,
  default_capacity INTEGER NOT NULL DEFAULT 1,
  default_line_capacity INTEGER,
  default_external_capacity INTEGER,
  default_buffer_capacity INTEGER NOT NULL DEFAULT 0,
  google_calendar_connection_id TEXT REFERENCES google_calendar_connections (id) ON DELETE SET NULL,
  slot_interval_minutes INTEGER NOT NULL DEFAULT 60,
  timezone TEXT NOT NULL DEFAULT 'Asia/Tokyo',
  is_active INTEGER NOT NULL DEFAULT 1,
  display_order INTEGER NOT NULL DEFAULT 0,
  metadata TEXT NOT NULL DEFAULT '{}',
  created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f', 'now', '+9 hours')),
  updated_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f', 'now', '+9 hours'))
);

CREATE TABLE IF NOT EXISTS reservation_menus (
  id TEXT PRIMARY KEY,
  resource_id TEXT NOT NULL REFERENCES reservation_resources (id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  description TEXT,
  duration_minutes INTEGER NOT NULL DEFAULT 60,
  unit_type TEXT NOT NULL DEFAULT 'person'
    CHECK (unit_type IN ('person', 'group', 'seat', 'table')),
  min_people INTEGER NOT NULL DEFAULT 1,
  max_people INTEGER,
  price_adult INTEGER,
  price_child INTEGER,
  price_infant INTEGER,
  price_under_three INTEGER,
  capacity_count_adult INTEGER NOT NULL DEFAULT 1 CHECK (capacity_count_adult IN (0, 1)),
  capacity_count_child INTEGER NOT NULL DEFAULT 1 CHECK (capacity_count_child IN (0, 1)),
  capacity_count_infant INTEGER NOT NULL DEFAULT 1 CHECK (capacity_count_infant IN (0, 1)),
  capacity_count_under_three INTEGER NOT NULL DEFAULT 0 CHECK (capacity_count_under_three IN (0, 1)),
  form_fields TEXT NOT NULL DEFAULT '[]',
  is_active INTEGER NOT NULL DEFAULT 1,
  display_order INTEGER NOT NULL DEFAULT 0,
  metadata TEXT NOT NULL DEFAULT '{}',
  created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f', 'now', '+9 hours')),
  updated_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f', 'now', '+9 hours'))
);

CREATE TABLE IF NOT EXISTS reservation_schedules (
  id TEXT PRIMARY KEY,
  resource_id TEXT NOT NULL REFERENCES reservation_resources (id) ON DELETE CASCADE,
  day_of_week INTEGER NOT NULL CHECK (day_of_week BETWEEN 0 AND 6),
  start_time TEXT NOT NULL,
  end_time TEXT NOT NULL,
  slot_interval_minutes INTEGER NOT NULL DEFAULT 60,
  default_capacity INTEGER NOT NULL DEFAULT 1,
  default_line_capacity INTEGER,
  default_external_capacity INTEGER,
  default_buffer_capacity INTEGER NOT NULL DEFAULT 0,
  is_active INTEGER NOT NULL DEFAULT 1,
  created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f', 'now', '+9 hours')),
  updated_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f', 'now', '+9 hours'))
);

CREATE TABLE IF NOT EXISTS reservation_slots (
  id TEXT PRIMARY KEY,
  resource_id TEXT NOT NULL REFERENCES reservation_resources (id) ON DELETE CASCADE,
  date TEXT NOT NULL,
  start_at TEXT NOT NULL,
  end_at TEXT NOT NULL,
  total_capacity INTEGER NOT NULL CHECK (total_capacity >= 0),
  line_capacity INTEGER CHECK (line_capacity IS NULL OR line_capacity >= 0),
  external_capacity INTEGER CHECK (external_capacity IS NULL OR external_capacity >= 0),
  buffer_capacity INTEGER NOT NULL DEFAULT 0 CHECK (buffer_capacity >= 0),
  reserved_count INTEGER NOT NULL DEFAULT 0 CHECK (reserved_count >= 0),
  line_reserved_count INTEGER NOT NULL DEFAULT 0 CHECK (line_reserved_count >= 0),
  external_reserved_count INTEGER NOT NULL DEFAULT 0 CHECK (external_reserved_count >= 0),
  status TEXT NOT NULL DEFAULT 'open'
    CHECK (status IN ('open', 'closed', 'sold_out', 'hidden')),
  note TEXT,
  created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f', 'now', '+9 hours')),
  updated_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f', 'now', '+9 hours')),
  UNIQUE(resource_id, start_at, end_at)
);

CREATE TABLE IF NOT EXISTS reservation_blackouts (
  id TEXT PRIMARY KEY,
  resource_id TEXT REFERENCES reservation_resources (id) ON DELETE CASCADE,
  start_at TEXT NOT NULL,
  end_at TEXT NOT NULL,
  reason TEXT,
  created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f', 'now', '+9 hours'))
);

CREATE TABLE IF NOT EXISTS reservations (
  id TEXT PRIMARY KEY,
  line_account_id TEXT REFERENCES line_accounts (id) ON DELETE SET NULL,
  user_id TEXT REFERENCES users (id) ON DELETE SET NULL,
  friend_id TEXT REFERENCES friends (id) ON DELETE SET NULL,
  slot_id TEXT NOT NULL REFERENCES reservation_slots (id) ON DELETE RESTRICT,
  source TEXT NOT NULL DEFAULT 'line'
    CHECK (source IN ('line', 'web', 'jalan', 'phone', 'gmail', 'admin', 'mcp')),
  capacity_channel TEXT NOT NULL DEFAULT 'line'
    CHECK (capacity_channel IN ('line', 'external', 'manual')),
  external_reservation_id TEXT,
  dedupe_key TEXT,
  title TEXT NOT NULL,
  reservation_date TEXT NOT NULL,
  start_at TEXT NOT NULL,
  end_at TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'confirmed'
    CHECK (status IN ('pending', 'confirmed', 'cancelled', 'completed', 'no_show')),
  adult_count INTEGER NOT NULL DEFAULT 0 CHECK (adult_count >= 0),
  child_count INTEGER NOT NULL DEFAULT 0 CHECK (child_count >= 0),
  infant_count INTEGER NOT NULL DEFAULT 0 CHECK (infant_count >= 0),
  under_three_count INTEGER NOT NULL DEFAULT 0 CHECK (under_three_count >= 0),
  total_people INTEGER NOT NULL DEFAULT 1 CHECK (total_people > 0),
  capacity_people INTEGER NOT NULL DEFAULT 1 CHECK (capacity_people > 0),
  customer_name_snapshot TEXT,
  customer_phone_snapshot TEXT,
  customer_email_snapshot TEXT,
  cancel_reason TEXT,
  form_data TEXT NOT NULL DEFAULT '{}',
  metadata TEXT NOT NULL DEFAULT '{}',
  created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f', 'now', '+9 hours')),
  updated_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f', 'now', '+9 hours'))
);

CREATE TABLE IF NOT EXISTS reservation_items (
  id TEXT PRIMARY KEY,
  reservation_id TEXT NOT NULL REFERENCES reservations (id) ON DELETE CASCADE,
  menu_id TEXT REFERENCES reservation_menus (id) ON DELETE SET NULL,
  resource_id TEXT REFERENCES reservation_resources (id) ON DELETE SET NULL,
  name_snapshot TEXT NOT NULL,
  quantity INTEGER NOT NULL DEFAULT 1,
  adult_count INTEGER NOT NULL DEFAULT 0,
  child_count INTEGER NOT NULL DEFAULT 0,
  infant_count INTEGER NOT NULL DEFAULT 0,
  under_three_count INTEGER NOT NULL DEFAULT 0,
  capacity_people INTEGER NOT NULL DEFAULT 1,
  unit_price INTEGER,
  amount INTEGER,
  metadata TEXT NOT NULL DEFAULT '{}',
  created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f', 'now', '+9 hours'))
);

CREATE TABLE IF NOT EXISTS reservation_events (
  id TEXT PRIMARY KEY,
  reservation_id TEXT NOT NULL REFERENCES reservations (id) ON DELETE CASCADE,
  event_type TEXT NOT NULL
    CHECK (event_type IN ('created', 'updated', 'confirmed', 'cancelled', 'completed', 'no_show', 'sync_failed', 'imported')),
  actor_type TEXT NOT NULL DEFAULT 'system'
    CHECK (actor_type IN ('customer', 'admin', 'gas', 'mcp', 'system')),
  actor_id TEXT,
  before_payload TEXT,
  after_payload TEXT,
  created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f', 'now', '+9 hours'))
);

CREATE TABLE IF NOT EXISTS visits (
  id TEXT PRIMARY KEY,
  user_id TEXT REFERENCES users (id) ON DELETE SET NULL,
  reservation_id TEXT REFERENCES reservations (id) ON DELETE SET NULL,
  visited_at TEXT NOT NULL,
  party_size INTEGER,
  spend_amount INTEGER,
  memo TEXT,
  metadata TEXT NOT NULL DEFAULT '{}',
  created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f', 'now', '+9 hours')),
  UNIQUE(reservation_id)
);

CREATE TABLE IF NOT EXISTS external_reservation_sources (
  id TEXT PRIMARY KEY,
  source TEXT NOT NULL CHECK (source IN ('jalan', 'gmail', 'phone', 'manual')),
  event_type TEXT NOT NULL DEFAULT 'unknown'
    CHECK (event_type IN ('created', 'updated', 'cancelled', 'unknown')),
  external_id TEXT,
  dedupe_key TEXT,
  reservation_id TEXT REFERENCES reservations (id) ON DELETE SET NULL,
  raw_text TEXT,
  parsed_payload TEXT NOT NULL DEFAULT '{}',
  parse_status TEXT NOT NULL DEFAULT 'pending'
    CHECK (parse_status IN ('pending', 'parsed', 'imported', 'needs_review', 'failed', 'duplicate', 'ignored')),
  received_at TEXT,
  last_error TEXT,
  created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f', 'now', '+9 hours')),
  updated_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f', 'now', '+9 hours'))
);

CREATE TABLE IF NOT EXISTS external_sync_tasks (
  id TEXT PRIMARY KEY,
  reservation_id TEXT REFERENCES reservations (id) ON DELETE CASCADE,
  slot_id TEXT REFERENCES reservation_slots (id) ON DELETE SET NULL,
  provider TEXT NOT NULL CHECK (provider IN ('jalan', 'google_calendar')),
  task_type TEXT NOT NULL CHECK (task_type IN ('reduce_capacity', 'restore_capacity', 'create_event', 'cancel_event', 'review')),
  adjustment_count INTEGER,
  status TEXT NOT NULL DEFAULT 'pending'
    CHECK (status IN ('pending', 'done', 'failed', 'skipped')),
  note TEXT,
  last_error TEXT,
  created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f', 'now', '+9 hours')),
  completed_at TEXT
);

CREATE INDEX IF NOT EXISTS idx_reservation_profiles_status ON reservation_customer_profiles (status);
CREATE INDEX IF NOT EXISTS idx_reservation_resources_account ON reservation_resources (line_account_id);
CREATE INDEX IF NOT EXISTS idx_reservation_menus_resource ON reservation_menus (resource_id, is_active, display_order);
CREATE INDEX IF NOT EXISTS idx_reservation_schedules_resource ON reservation_schedules (resource_id, day_of_week);
CREATE INDEX IF NOT EXISTS idx_reservation_slots_resource_date ON reservation_slots (resource_id, date, start_at);
CREATE INDEX IF NOT EXISTS idx_reservation_slots_status ON reservation_slots (status);
CREATE INDEX IF NOT EXISTS idx_reservations_date ON reservations (reservation_date, status);
CREATE INDEX IF NOT EXISTS idx_reservations_user ON reservations (user_id);
CREATE INDEX IF NOT EXISTS idx_reservations_slot ON reservations (slot_id, status);
CREATE INDEX IF NOT EXISTS idx_reservations_source_external ON reservations (source, external_reservation_id);
CREATE INDEX IF NOT EXISTS idx_reservations_source_dedupe ON reservations (source, dedupe_key);
CREATE UNIQUE INDEX IF NOT EXISTS uniq_reservations_external_id
  ON reservations (source, external_reservation_id)
  WHERE external_reservation_id IS NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS uniq_reservations_dedupe_key
  ON reservations (source, dedupe_key)
  WHERE dedupe_key IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_reservation_events_reservation ON reservation_events (reservation_id, created_at);
CREATE INDEX IF NOT EXISTS idx_external_sources_external ON external_reservation_sources (source, external_id);
CREATE INDEX IF NOT EXISTS idx_external_sources_dedupe ON external_reservation_sources (source, dedupe_key);
CREATE UNIQUE INDEX IF NOT EXISTS uniq_external_sources_external_id
  ON external_reservation_sources (source, external_id)
  WHERE external_id IS NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS uniq_external_sources_dedupe_key
  ON external_reservation_sources (source, dedupe_key)
  WHERE dedupe_key IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_external_sync_tasks_status ON external_sync_tasks (provider, status, created_at);

CREATE TABLE IF NOT EXISTS gmail_import_rules (
  id TEXT PRIMARY KEY,
  connection_id TEXT NOT NULL REFERENCES google_calendar_connections (id) ON DELETE CASCADE,
  source_name TEXT NOT NULL DEFAULT 'jalan' CHECK (source_name IN ('jalan')),
  name TEXT NOT NULL,
  from_email TEXT,
  query TEXT,
  unprocessed_label_id TEXT NOT NULL,
  processed_label_id TEXT NOT NULL,
  review_label_id TEXT NOT NULL,
  failed_label_id TEXT NOT NULL,
  resource_id TEXT REFERENCES reservation_resources (id) ON DELETE SET NULL,
  menu_id TEXT REFERENCES reservation_menus (id) ON DELETE SET NULL,
  max_results INTEGER NOT NULL DEFAULT 10 CHECK (max_results BETWEEN 1 AND 50),
  is_active INTEGER NOT NULL DEFAULT 1,
  last_run_at TEXT,
  created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f', 'now', '+9 hours')),
  updated_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%f', 'now', '+9 hours'))
);

CREATE INDEX IF NOT EXISTS idx_gmail_import_rules_active
  ON gmail_import_rules (is_active, source_name);

CREATE TABLE IF NOT EXISTS gmail_import_runs (
  id TEXT PRIMARY KEY,
  rule_id TEXT NOT NULL REFERENCES gmail_import_rules (id) ON DELETE CASCADE,
  started_at TEXT NOT NULL,
  finished_at TEXT,
  status TEXT NOT NULL DEFAULT 'running' CHECK (status IN ('running', 'success', 'partial_failed', 'failed')),
  fetched_count INTEGER NOT NULL DEFAULT 0,
  imported_count INTEGER NOT NULL DEFAULT 0,
  review_count INTEGER NOT NULL DEFAULT 0,
  failed_count INTEGER NOT NULL DEFAULT 0,
  last_error TEXT
);

CREATE INDEX IF NOT EXISTS idx_gmail_import_runs_rule
  ON gmail_import_runs (rule_id, started_at);

CREATE TABLE IF NOT EXISTS rich_menu_assets (
  rich_menu_id TEXT PRIMARY KEY,
  line_account_id TEXT,
  image_key TEXT NOT NULL,
  image_url TEXT NOT NULL,
  mime_type TEXT NOT NULL,
  size INTEGER,
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  updated_at TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE INDEX IF NOT EXISTS idx_rich_menu_assets_account
  ON rich_menu_assets (line_account_id);
